# This is a basic workflow to help you get started with Actions

name: Build and Push image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-n-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Image
        run: docker build -t orangenal/recipes-maven:latest RecipesMaven/
      -
        name: Push Image
        run: docker push orangenal/recipes-maven:latest
      -
        name: Logout from repo
        run: docker logout
  deploy:
      needs: build-n-push
      runs-on: ubuntu-latest
      steps:
        -
          name: ssh-pipeline
          uses: cross-the-world/ssh-pipeline@v1.2.0
          with:
            # ssh remote host
            host: ${{ secrets.HOST }}
            # ssh remote port
            port: ${{ secrets.PORT }}
            # ssh remote user
            user: ${{ secrets.USERNAME }}
            # content of ssh private key. ex raw content of ~/.ssh/id_rsa
            key: ${{ secrets.KEY }}
            script: |
              cd ${{ secrets.APP_PATH }}
              docker-compose down
              docker image rm orangenal/recipes-maven
              docker system prune --volumes -a --force
              docker pull orangenal/recipes-maven:latest
              docker-compose up -d
